[package]
name = "feed_forward_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tch = "0.13.0"
colored = "2.0.0"
indicatif = "0.17.5"
